
--TẠO PROCEDURE

-- ĐĂNG NHẬP
create procedure DANG_NHAP @TENDANGNHAP NVARCHAR(50), @MATKHAU NCHAR(20)
AS
	if (not exists (SELECT * FROM KHACHHANG WHERE  TENDANGNHAP = @TENDANGNHAP AND MATKHAU = @MATKHAU))
		return 0
	else
	return 1

	--lấy số lượng khách hàng
create procedure SL_KHACH
AS
	declare @a int
	SELECT @a = COUNT(*) FROM KHACHHANG
	return @a
--SỐ LƯỢNG MA DP
create procedure SL_DAT
AS
	declare @a int
	SELECT @a = COUNT(*) FROM DATPHONG
	return @a

--SỐ LƯỢNG HOA DON
create procedure SL_HOADON
AS
	declare @a int
	SELECT @a = COUNT(*) FROM HOADON
	return @a

	
--LẤY BẢNG TRONG CSDL
create procedure LAY_DU_LIEU @tenbang nchar(20)
AS
	if (@tenbang = 'KHACHHANG') return SELECT *FROM KHACHHANG
	if (@tenbang = 'KHACHSAN') return SELECT *FROM KHACHSAN
	if (@tenbang = 'PHONG') return SELECT *FROM PHONG
	if (@tenbang = 'DATPHONG') return SELECT *FROM DATPHONG
	if (@tenbang = 'TRANGTHAIPHONG') return SELECT *FROM TRANGTHAIPHONG
	if (@tenbang = 'HOADON') return SELECT *FROM HOADON
	if (@tenbang = 'LOAIPHONG') return SELECT *FROM LOAIPHONG
	return null

-- ĐIỀN THÔNG TIN KHÁCH HÀNG
alter procedure THEM_KHACH_HANG @MAKH nchar(10), @HOTEN NVARCHAR(50), @TENDANGNHAP NVARCHAR(50),
			@MATKHAU NCHAR(20), @CMND NCHAR(11), @DIACHI NVARCHAR(50), @DIENTHOAI NCHAR(12), @MOTA  NVARCHAR(50), @EMAIL NCHAR(30)
as
	if (not exists (SELECT MAKH FROM KHACHHANG WHERE TENDANGNHAP=@TENDANGNHAP ))
	begin
		if (not exists ( SELECT MAKH FROM KHACHHANG WHERE MAKH = @MAKH))
			INSERT INTO KHACHHANG (MAKH,HOTEN,TENDANGNHAP,MATKHAU,CMND,DIACHI,DIENTHOAI,MOTA,EMAIL) VALUES (@MAKH,@HOTEN,@TENDANGNHAP,@MATKHAU,@CMND,@DIACHI,@DIENTHOAI,@MOTA,@EMAIL)
		else RETURN 0
	end
	else RETURN 0
	RETURN 1

-- TÌM KIẾM KHÁCH SẠN
	-- Giá cả, thành phố
create procedure TIMKIEM_GIA @GIA FLOAT, @THANHPHO NVARCHAR(20)
AS
		SELECT * FROM KHACHSAN WHERE @GIA = GIATB AND @THANHPHO = THANHPHO
		
	-- Hạng sao, thành phố
create procedure TIMKIEM_SAO @SOSAO INT, @THANHPHO NVARCHAR(20)
AS
		SELECT * FROM KHACHSAN WHERE @SOSAO = SOSAO AND @THANHPHO = THANHPHO


--ĐẶT PHÒNG
	-- Lấy trạng thái phòng ( Chưa sử dụng, Đang sử dụng hay bảo trì)
create procedure LAY_TRANGTHAI @MAPHONG NCHAR(10)
AS
	SELECT TINHTRANG FROM TRANGTHAIPHONG WHERE @MAPHONG = MAPHONG

	-- Kiểm tra trạng thái phòng ( truyền vào tham số @TINHTRANG = "Còn trống", "Chưa sử dụng")
create procedure KIEMTRA_TRANGTHAI @MAPHONG NCHAR(10), @TINHTRANG NVARCHAR(30)
AS
	if ((SELECT TINHTRANG FROM TRANGTHAIPHONG WHERE @MAPHONG = MAPHONG) = @TINHTRANG)
	return 1
	else
	return 0

	--Lấy danh sách phòng trống
create procedure LAY_PHONG_TRONG @MAKS NCHAR(10)
AS
	SELECT P.MAPHONG, LP.TENLOAIPHONG, P.SOPHONG FROM PHONG P,TRANGTHAIPHONG TP,LOAIPHONG LP WHERE LP.MAKS = @MAKS AND LP.MALOAIPHONG = P.LOAIPHONG AND P.MAPHONG = TP.MAPHONG AND TP.TINHTRANG = N'còn trống'

	
	-- Đặt phòng
create procedure DAT_PHONG @MADP NCHAR(10), @MAPHONG NCHAR(10), @MAKH NCHAR(10), @NGAYBATDAU DATETIME, 
					@NGAYTRAPHONG DATETIME, @NGAYDAT DATETIME, @DONGIA INT, @MOTA NVARCHAR(50), @TINHTRANG NVARCHAR(20)
AS
	if (not exists (SELECT MADP FROM DATPHONG WHERE @MADP = MADP))
	INSERT INTO DATPHONG(MADP,MAPHONG,MAKH,NGAYBATDAU,NGAYTRAPHONG,NGAYDAT,DONGIA,MOTA,TINHTRANG) 
		VALUES (@MADP,@MAPHONG,@MAKH,@NGAYBATDAU,@NGAYTRAPHONG,@NGAYDAT,@DONGIA,@MOTA,@TINHTRANG)
	else RETURN 0
	RETURN 1

	--Lấy danh sach đặt phòng của khách sạn
create procedure LAY_DAT_PHONG @MAKS nchar(10)
AS
	SELECT DP.MADP, DP.MAKH, DP.NGAYBATDAU, DP.NGAYTRAPHONG, DP.DONGIA FROM DATPHONG DP, PHONG P, LOAIPHONG LP WHERE LP.MAKS = @MAKS AND LP.MALOAIPHONG = P.LOAIPHONG AND P.MAPHONG = DP.MAPHONG

	-- Thành phố
create procedure TIMKIEM_THANHPHO @THANHPHO NVARCHAR(20)
AS
	SELECT * FROM KHACHSAN WHERE @THANHPHO = THANHPHO


--LẬP HÓA ĐƠN
create procedure LAP_HOA_DON @MAHD NCHAR(10),@NGAYTHANHTOAN date,@TONGTIEN FLOAT,@MADP NCHAR(10)
AS
	if (not exists (SELECT MAHD FROM HOADON WHERE MAHD = @MAHD))
		INSERT INTO HOADON(MAHD,NGAYTHANHTOAN,TONGTIEN,MADP) VALUES (@MAHD,@NGAYTHANHTOAN,@TONGTIEN,@MADP)
	else RETURN 0
	RETURN 1

--TÌM KIẾM THÔNG TIN HÓA ĐƠN
	-- Theo Mã khách hàng
create procedure TIM_HOADON_MAKH @MAKH NCHAR(10)
AS
	
	SELECT MAHD,NGAYTHANHTOAN,TONGTIEN FROM HOADON HD,DATPHONG DP WHERE DP.MADP = HD.MADP AND @MAKH = MAKH

	-- Theo ngày lập (cái này dùng để xem hiệu quả index)
create procedure TIM_HOADON_NGAY @NGAYTHANHTOAN date
AS
	SELECT MAHD,NGAYTHANHTOAN,TONGTIEN FROM HOADON WHERE @NGAYTHANHTOAN = NGAYTHANHTOAN

		-- Tìm kiếm hóa đơn theo ngày lập (dùng cho ứng dụng)
alter procedure TIM_HOADON_NGAY @NGAY int, @THANG int, @NAM int 
AS
	SELECT MAHD,NGAYTHANHTOAN,TONGTIEN FROM HOADON WHERE YEAR(NGAYTHANHTOAN) = @NAM AND MONTH(NGAYTHANHTOAN) = @THANG AND DAY(NGAYTHANHTOAN) = @NGAY

	-- tìm kiếm hóa đơn theo tổng tiền
alter procedure TIM_HOADON_TIEN @TIEN int
as
	select MAHD,NGAYTHANHTOAN,TONGTIEN from HOADON where TONGTIEN=@TIEN
	--Lấy mã kh
create procedure LAY_MA_KH @MAKH nchar(10)
AS
	SELECT MAKH FROM KHACHHANG WHERE TENDANGNHAP = @MAKH

	--Lấy mô tả

create procedure LAY_MO_TA @MAPHONG nchar(10)
AS
	SELECT LP.MOTA FROM LOAIPHONG LP,PHONG P WHERE LP.MALOAIPHONG = P.LOAIPHONG AND P.MAPHONG = @MAPHONG

	--Lấy đơn giá
create procedure LAY_DON_GIA @MAPHONG nchar(10)
AS
	SELECT LP.DONGIA FROM LOAIPHONG LP,PHONG P WHERE LP.MALOAIPHONG = P.LOAIPHONG AND P.MAPHONG = @MAPHONG

	--Lấy danh sách thành phố
create procedure LAY_DS_THANHPHO 
as 
	SELECT DISTINCT THANHPHO FROM KHACHSAN

--BÁO CÁO THỐNG KÊ HÓA ĐƠN

	-- Tính doanh thu
	create procedure TINH_DOANHTHU @THANG int, @NAM int
as
	if (@THANG = 0)
		SELECT SUM(TONGTIEN) as TONGDOANHTHU FROM HOADON WHERE @NAM =  year(NGAYTHANHTOAN)
	else
		SELECT SUM(TONGTIEN) as TONGDOANHTHU FROM HOADON WHERE @THANG = month(NGAYTHANHTOAN) and @NAM =  year(NGAYTHANHTOAN)

		-- Lấy danh sách hóa đơn
create procedure THONGKE_HOADON_THANG_NAM @THANG int, @NAM int
as 
	if (@THANG = 0)
		SELECT MAHD, NGAYTHANHTOAN, TONGTIEN, MADP FROM HOADON WHERE @NAM =  year(NGAYTHANHTOAN)
	else
		SELECT MAHD, NGAYTHANHTOAN, TONGTIEN, MADP FROM HOADON WHERE @THANG = month(NGAYTHANHTOAN) and @NAM =  year(NGAYTHANHTOAN) 

	

	--Lấy danh sách phòng trống theo thành phố, số sao
create procedure LAY_DS_PHONGTRONG @THANHPHO nvarchar(20), @SOSAO int
as
	SELECT KHACHSAN.MAKS, TENKS, MALOAIPHONG, TENLOAIPHONG, SLTRONG FROM KHACHSAN, LOAIPHONG WHERE @THANHPHO = THANHPHO and @SOSAO = SOSAO and KHACHSAN.MAKS = LOAIPHONG.MAKS order by KHACHSAN.MAKS 



